name: .NET Build

on:
  push:
    branches: [ master ]
    paths: ['dotnet-webapi/**.cs'] 
  pull_request:
    branches: [ master ]
    paths: ['dotnet-webapi/**.cs']
  workflow_dispatch:
    
env:
  DOTNET_PROJECT_PATH: './dotnet-webapi'
  PUBLISH_PATH: './publish'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore '${{ env.DOTNET_PROJECT_PATH }}/dotnet-webapi.csproj'
    - name: Build
      run: dotnet build '${{ env.DOTNET_PROJECT_PATH }}/dotnet-webapi.csproj' --no-restore
    - name: Publish
      run: dotnet publish '${{ env.DOTNET_PROJECT_PATH }}/dotnet-webapi.csproj' -o '${{ env.PUBLISH_PATH }}'
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: dotnet-webapi-demo
        # A file, directory or wildcard pattern that describes what to upload
        path: '${{ env.PUBLISH_PATH }}'
  
  deploy_to_dev:
    
    runs-on:  ubuntu-latest
    environment: dev
    needs: build
    steps:
     - name: Download a Build Artifact
       uses: actions/download-artifact@v2.0.10
       with:
        # Artifact name
        name: dotnet-webapi-demo
        path: '${{ env.PUBLISH_PATH }}'
    
     - name: Azure WebApp
       uses: Azure/webapps-deploy@v2
       with:
        # Name of the Azure Web App
        app-name: webkovaicotrial
        # Applies to Web Apps(Windows and Linux) and Web App Containers(linux). Multi container scenario not supported. Publish profile (*.publishsettings) file contents with Web Deploy secrets
        publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}
        package: '${{ env.PUBLISH_PATH }}'

  deploy_to_prod:
    
    runs-on:  ubuntu-latest
    environment: prod
    needs: deploy_to_dev
    steps:
     - name: Download a Build Artifact
       uses: actions/download-artifact@v2.0.10
       with:
        # Artifact name
        name: dotnet-webapi-demo
        path: '${{ env.PUBLISH_PATH }}'
    
     - name: Azure WebApp
       uses: Azure/webapps-deploy@v2
       with:
        # Name of the Azure Web App
        app-name: webkovaicodemoprod
        # Applies to Web Apps(Windows and Linux) and Web App Containers(linux). Multi container scenario not supported. Publish profile (*.publishsettings) file contents with Web Deploy secrets
        publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}
        package: '${{ env.PUBLISH_PATH }}'
    
      
